### ISSUE TITLE
provided image not working on newer Raspberry Pi 4B lots?

### ISSUE THREAD

**Issue by hnakayam** [notro/gud#17]
Thanks for the efforts you provided! 

I just tried using the Raspberry Pi (not lite) image v1.00 provided, and some Raspberry Pi4 (model B / 4GB) lots work perfect, but some Raspberry Pi4 lots (recently purchased) the GUD portion of the system does not work. (still Raspberry Pi OS work though...)

So Is there a "hardware" difference in the new Raspberry Pi 4 production lots?
Some Raspberry Pi stores say something like "Please use Raspbian 2019-06-20 NOOBS 3.1.1 (2019-06-24) or later". Is this a problem?

note: I have also tried the image provided with my recently purchased Raspberry Pi ZERO V1.3 hardware and this ZERO worked very well.

**Comment by notro** [comment]
I see that there was a new Pi4 revision c03115 out in Q1 2022: https://elinux.org/RPi_HardwareHistory#Board_Revision_History

This forum post states that a new firmware is needed for the 1.5 pcb revision: https://forums.raspberrypi.com/viewtopic.php?t=329625

Please try and copy ```fixup4.dat``` and ```start4.elf``` from the Raspberry Pi OS boot partition and see if that works.
I hope it's enough to update the firmware and that it's not necessary to update the kernel.

**Comment by hnakayam** [comment]
I checked my Raspberry Pi4 revision and turned out it was c03115.

Hardware        : BCM2835
Revision        : c03115
Serial          : 100000008a59e368
Model           : Raspberry Pi 4 Model B Rev 1.5

So, I updated the "fixup4.dat" and "start4.elf" in the boot partition and now it works on Ubuntu host!
Thank you very much for your valuable information.

**Comment by notro** [comment]
Thanks for reporting back, new release out that should fix this: https://github.com/notro/gud/releases/tag/v1.01
